export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Lagos Streetwear Hoodie",
    slug: "lagos-streetwear-hoodie",
    description: "Premium cotton hoodie with Lagos coordinates. Part of our Boldnook Originals collection.",
    image: { sourceUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800" },
    price: "₦25,000",
    regularPrice: "₦30,000",
    salePrice: "₦25,000",
    categories: ["Men", "Clothing", "Streetwear"],
    brand: "Boldnook Originals",
  },
  {
    id: "2",
    name: "Asoebi Silk Wrap Dress",
    slug: "asoebi-silk-wrap-dress",
    description: "Elegant silk wrap dress perfect for any owambe. Handcrafted in Lagos.",
    image: { sourceUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800" },
    price: "₦45,000",
    regularPrice: "₦45,000",
    salePrice: null,
    categories: ["Women", "Clothing", "Asoebi"],
    brand: "Nigerian Label",
  },
  {
    id: "3",
    name: "Urban Kaftan Set",
    slug: "urban-kaftan-set",
    description: "Modern take on the traditional kaftan. Slim fit, premium linen.",
    image: { sourceUrl: "https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?auto=format&fit=crop&q=80&w=800" },
    price: "₦35,000",
    regularPrice: "₦35,000",
    salePrice: null,
    categories: ["Men", "Clothing", "Traditional"],
    brand: "Boldnook Studio",
  },
  {
    id: "4",
    name: "Classic Melanin Glow Serum",
    slug: "melanin-glow-serum",
    description: "Hydrating serum formulated for melanin-rich skin.",
    image: { sourceUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800" },
    price: "₦12,500",
    regularPrice: "₦15,000",
    salePrice: "₦12,500",
    categories: ["Beauty", "Skincare"],
    brand: "Boldnook Beauty",
  },
];

export const MOCK_CATEGORIES = [
  { name: "Women", slug: "women", description: "Shop women's fashion on Boldnook." },
  { name: "Men", slug: "men", description: "Shop men's fashion on Boldnook." },
  { name: "Asoebi", slug: "asoebi", description: "Wedding? Owambe? Graduation? Shop Boldnook's occasion edit." },
  { name: "Nigerian Labels", slug: "nigerian-labels", description: "Support Nigerian fashion." },
  { name: "Sale", slug: "sale", description: "Big brands. Better prices." },
];
